use_frameworks!

platform :ios, '9.0'

target 'PJCocoaPodsTestProject_Example' do
  pod 'PJCocoaPodsTestProject', :path => '../'

  target 'PJCocoaPodsTestProject_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
